services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: imagen-pparticipativos:latest
    container_name: pparticipativos-container
    ports:
      - "8083:3000"
    env_file:
      - .env
    depends_on: []
    restart: unless-stopped
